### ISSUE TITLE
Sequence email to be sent last

### ISSUE THREAD

**Issue by roncewind** [Senzing/aws-cloudformation-ecs-poc-simple#149]
Ran into a situation where the admin user was using the web app before the stack had completely come up.  This, apparently, caused the g2 config to fail.  Let's see if we can make the email a dependent of whatever is done last.

**Comment by roncewind** [comment]
Sequencing this could challenging given that the G2 config only run if stream producer runs.  Maybe we should augment the email to warn folks not to use the web app before the stack creation is completed.

**Comment by roncewind** [comment]
@mahchiahui yes, we could do that, but the question becomes is the juice worth the squeeze?  

the Cognito email will get sent when the user is created.  I'm not sure it makes sense for us to send a second email or to set up infrastructure to send a second email just to tell the user the stack is up.  Could be that there's not much for the CFT to set up an SNS topic, but there will be new permissions needed.  Could be that it doesn't cost the user anything to have that infrastructure set up.  

I don't think all the trouble is worth it.  IF the user has notifications already set up, then when deploying the CFT they can use the Advanced options -> Notification options to trigger their SNS topic.  

Any compelling reason to go through the extra effort for our "sample" CFTs?

**Comment by mahchiahui** [comment]
Ah I think the thought I had back then was that since it was challenging in sequencing a notification after the stack creation is completed (might be because we use cognito to send out the email), we could use AWS SNS to send out a notification, which can be customized to an email or SMS after the process is done.

I was thinking that it provide for a better experience for the customer using it, so that they wouldn't have to keep refreshing the cloudformation page and will receive a notification when everything is done.

**Comment by roncewind** [comment]
Yup, agreed.  I looked into SNS a bit ago, but I didn't have perms to create an SNS topic.  All in all, it seems like more trouble than it's worth.  Not to mention that if the end user wants the SNS notification, they can configure it themself when they create the stack.  IF we were providing more than just "sample" CFTs, then perhaps, setting up SNS and the costs association with it would be worth it for a single email?

**Comment by roncewind** [comment]
Decision point:  add warning to Cognito email

**Comment by roncewind** [comment]
PR merged
