### ISSUE TITLE
Post Install

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/aws-cloudformation-ecs-poc-simple#81]
I have a couple of new install queries:

The Cloudformation installer spins up 3 databases with 8 total capacity units...
1) is this normal / required
2) looking for a more economical way to do this - please advise

<img width="1264" alt="Screenshot 2021-05-11 at 10 33 41" src="https://user-images.githubusercontent.com/7249713/117785359-cc4c3a00-b244-11eb-98dc-39042babd242.png">

The Cloudformation installer adds a couple of Lambdas...
Are they used for running Senzing, or only used during the install?

<img width="1170" alt="Screenshot 2021-05-11 at 10 43 30" src="https://user-images.githubusercontent.com/7249713/117786414-c145d980-b245-11eb-9be4-25d9169f834e.png">

There 8 tasks running in the Cluster spun up with Cloudformation...
I guess we only need "api-server" for running an API only system? i.e. We have Lambda 1) adding new users, then 2) querying the created user to find any matches.

**Comment by docktermj** [comment]
Hi @christianswanepoel!

At the moment, we only have cloudformations for the 3-database configurations.   We had one database in past configurations, but customers were asking for speed, so we have been focused on the 3-database "sharded" approach.

That being said,  in https://github.com/Senzing/aws-cloudformation-ecs/issues/31 we are working on separating out the database definition from the Senzing application.   After that happens, there may be a way to give customers a choice of 1 or 3 databases for economy vs. speed.

The lambda functions that you list, and all lambda functions for that matter, are all used to perform the deployment, not the actual running of the deployment once it is up-and-running.

Since you are "adding new users" you'll also need the 'redoer" services.

**Comment by christianswanepoel** [comment]
Thank you as always.
Are you sure API Gateway uses the "redoer"?

I subscribed to https://github.com/Senzing/aws-cloudformation-ecs/issues/31

**Comment by brianmacy** [comment]
Some other things to note...
1. The assets in the Senzing Community are simply meant as working assets that you can leverage if you don't want to integrate with the embedded Senzing API directly.  Feel free to modify to your own needs.
2. If you don't have a real-time workload need, you could set the DBs to go completely offline automatically.

**Comment by docktermj** [comment]
@christianswanepoel Is this discussion complete?
